package visao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Conversor;

/**
 *
 * @author Müller Gonçalves
 * @since 16/04/2018 - 14:21
 * @version 1.0
 */
public class UICadConversor extends javax.swing.JFrame {

    /**
     * Creates new form UICadConversor
     */
    public UICadConversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDados = new javax.swing.JLayeredPane();
        jlReal = new javax.swing.JLabel();
        jlDolar = new javax.swing.JLabel();
        jlEuro = new javax.swing.JLabel();
        jtReal = new javax.swing.JTextField();
        jtDolar = new javax.swing.JTextField();
        jtEuro = new javax.swing.JTextField();
        jlBitcoin = new javax.swing.JLabel();
        jtBitcoin = new javax.swing.JTextField();
        jlConfirmacao = new javax.swing.JLayeredPane();
        jbConverter = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbConverRapida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jlReal.setText("Real:");

        jlDolar.setText("Dólar:");

        jlEuro.setText("Euro:");

        jtReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRealKeyPressed(evt);
            }
        });

        jtDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDolarKeyPressed(evt);
            }
        });

        jtEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEuroKeyPressed(evt);
            }
        });

        jlBitcoin.setText("Bitcoin:");

        jtBitcoin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtBitcoinKeyPressed(evt);
            }
        });

        jlDados.setLayer(jlReal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlDolar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlEuro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtReal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtDolar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtEuro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlBitcoin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtBitcoin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlDadosLayout = new javax.swing.GroupLayout(jlDados);
        jlDados.setLayout(jlDadosLayout);
        jlDadosLayout.setHorizontalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlBitcoin)
                    .addComponent(jlEuro)
                    .addComponent(jlDolar)
                    .addComponent(jlReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtReal)
                    .addComponent(jtDolar)
                    .addComponent(jtEuro)
                    .addComponent(jtBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlDadosLayout.setVerticalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlReal)
                    .addComponent(jtReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDolar)
                    .addComponent(jtDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEuro)
                    .addComponent(jtEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBitcoin)
                    .addComponent(jtBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jlConfirmacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirmação"));

        jbConverter.setText("Converter");
        jbConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConverterActionPerformed(evt);
            }
        });
        jbConverter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbConverterKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbConverRapida.setText("Conver. Rápida");
        jbConverRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConverRapidaActionPerformed(evt);
            }
        });
        jbConverRapida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbConverRapidaKeyPressed(evt);
            }
        });

        jlConfirmacao.setLayer(jbConverter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlConfirmacao.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlConfirmacao.setLayer(jbConverRapida, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlConfirmacaoLayout = new javax.swing.GroupLayout(jlConfirmacao);
        jlConfirmacao.setLayout(jlConfirmacaoLayout);
        jlConfirmacaoLayout.setHorizontalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConverRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jlConfirmacaoLayout.setVerticalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlConfirmacaoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConverter)
                    .addComponent(jbLimpar)
                    .addComponent(jbConverRapida)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDados)
                    .addComponent(jlConfirmacao))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConverterActionPerformed
        verificar();
        limpar();
    }//GEN-LAST:event_jbConverterActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbConverRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConverRapidaActionPerformed
        converterRapido();
    }//GEN-LAST:event_jbConverRapidaActionPerformed

    private void jbConverterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbConverterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificar();
            limpar();
        }
    }//GEN-LAST:event_jbConverterKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbConverRapidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbConverRapidaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            converterRapido();
        }
    }//GEN-LAST:event_jbConverRapidaKeyPressed

    private void jtRealKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRealKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtDolar.grabFocus();
        }
    }//GEN-LAST:event_jtRealKeyPressed

    private void jtDolarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDolarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtEuro.grabFocus();
        }
    }//GEN-LAST:event_jtDolarKeyPressed

    private void jtEuroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEuroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtBitcoin.grabFocus();
        }
    }//GEN-LAST:event_jtEuroKeyPressed

    private void jtBitcoinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBitcoinKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificar();
            limpar();
        }
    }//GEN-LAST:event_jtBitcoinKeyPressed
    Conversor objConversor = new Conversor();
    
    private void verificar(){
        
        objConversor.setReal(Double.parseDouble(jtReal.getText()));
        objConversor.setDolar(Double.parseDouble(jtDolar.getText()));
        objConversor.setEuro(Double.parseDouble(jtEuro.getText()));
        objConversor.setBitcoin(Double.parseDouble(jtBitcoin.getText()));
        
        JOptionPane.showMessageDialog(
                this,
                "Dados: \n" + objConversor.toString(),
                "Relatório",
                JOptionPane.PLAIN_MESSAGE);
    }
    
    private void limpar(){
        jtReal.setText(null);
        jtDolar.setText(null);
        jtEuro.setText(null);
        jtBitcoin.setText(null);
        jtReal.grabFocus();
    }
    
    private void converterRapido(){
        objConversor.setReal(Double.parseDouble(jtReal.getText()));
        objConversor.setDolar(Double.parseDouble(jtDolar.getText()));
        objConversor.setEuro(Double.parseDouble(jtEuro.getText()));
        objConversor.setBitcoin(Double.parseDouble(jtBitcoin.getText()));
        
        jtDolar.setText(Double.toString(objConversor.converterParaDolar()));
        jtEuro.setText(Double.toString(objConversor.converterParaEuro()));
        jtBitcoin.setText(Double.toString(objConversor.converterParaBitcoin()));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConverRapida;
    private javax.swing.JButton jbConverter;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlBitcoin;
    private javax.swing.JLayeredPane jlConfirmacao;
    private javax.swing.JLayeredPane jlDados;
    private javax.swing.JLabel jlDolar;
    private javax.swing.JLabel jlEuro;
    private javax.swing.JLabel jlReal;
    private javax.swing.JTextField jtBitcoin;
    private javax.swing.JTextField jtDolar;
    private javax.swing.JTextField jtEuro;
    private javax.swing.JTextField jtReal;
    // End of variables declaration//GEN-END:variables
}
