package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Pessoa;

/**
 *
 * @author Müller Gonçalves
 * @since 18/04/2018 - 18:16
 * @version 1.0
 */
public class UICadPessoa extends javax.swing.JFrame
{

    /**
     * Creates new form UICadPessoa
     */
    public UICadPessoa()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jlDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlPrefs = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jcRpg = new javax.swing.JCheckBox();
        jcMmorpg = new javax.swing.JCheckBox();
        jlConfirmacao = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jlPrefs.setText("Preferências:");

        jcRpg.setText("RPG");

        jcMmorpg.setText("MMORPG");

        jlDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlPrefs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jcRpg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jcMmorpg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlDadosLayout = new javax.swing.GroupLayout(jlDados);
        jlDados.setLayout(jlDadosLayout);
        jlDadosLayout.setHorizontalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlDadosLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlPrefs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcMmorpg)
                            .addComponent(jcRpg))))
                .addGap(75, 75, 75))
        );
        jlDadosLayout.setVerticalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPrefs)
                    .addComponent(jcRpg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcMmorpg)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jlConfirmacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbLimparActionPerformed(evt);
            }
        });

        jlConfirmacao.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlConfirmacao.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlConfirmacaoLayout = new javax.swing.GroupLayout(jlConfirmacao);
        jlConfirmacao.setLayout(jlConfirmacaoLayout);
        jlConfirmacaoLayout.setHorizontalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlConfirmacaoLayout.setVerticalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbCadastrar)
                .addComponent(jbLimpar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlConfirmacao)
                    .addComponent(jlDados))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCadastrarActionPerformed
    {//GEN-HEADEREND:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbLimparActionPerformed
    {//GEN-HEADEREND:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed
    
    private void cadastrar(){
        Pessoa objPessoa = new Pessoa();
        
        objPessoa.setNome(jtNome.getText());
        ArrayList<String> prefs = new ArrayList<>();
        
        if (jcRpg.isSelected()){
            prefs.add(jcRpg.getText());
        } else {
            prefs.add("-");
        }
        
        if (jcMmorpg.isSelected()){
            prefs.add(jcMmorpg.getText());
        } else {
            prefs.add("-");
        }
        
        objPessoa.setPrefs(prefs);
        
        JOptionPane.showMessageDialog(rootPane,
                "Dados: " + objPessoa.toString(),
                "Relatório",
                JOptionPane.PLAIN_MESSAGE);
    }
    
    private void limpar(){
        jtNome.setText(null);
        jcRpg.setSelected(false);
        jcMmorpg.setSelected(false);
        jtNome.grabFocus();         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UICadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UICadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UICadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UICadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UICadPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JCheckBox jcMmorpg;
    private javax.swing.JCheckBox jcRpg;
    private javax.swing.JLayeredPane jlConfirmacao;
    private javax.swing.JLayeredPane jlDados;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPrefs;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
