/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.JogoVO;
import servicos.JogoServicos;

/**
 *
 * @author Alunos
 */
public class GUICadJogo extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadJogo
     */
    public GUICadJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlDesenvolvedora = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jlClassificacao = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtDesenvolvedora = new javax.swing.JTextField();
        jtQuantidade = new javax.swing.JTextField();
        jtClassificacao = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jlConfirmacao = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Jogo");

        jlDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jlDesenvolvedora.setText("Desenvolvedora:");

        jlQuantidade.setText("Quantidade: ");

        jlClassificacao.setText("Classificação Etária: ");

        jlValor.setText("Valor:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });

        jtDesenvolvedora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDesenvolvedoraFocusLost(evt);
            }
        });

        jtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantidadeFocusLost(evt);
            }
        });

        jtClassificacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtClassificacaoFocusLost(evt);
            }
        });

        jtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorFocusLost(evt);
            }
        });

        jlDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlDesenvolvedora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlClassificacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtDesenvolvedora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtClassificacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtValor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlDadosLayout = new javax.swing.GroupLayout(jlDados);
        jlDados.setLayout(jlDadosLayout);
        jlDadosLayout.setHorizontalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValor))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlClassificacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtClassificacao))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtQuantidade))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlDesenvolvedora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDesenvolvedora))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jlDadosLayout.setVerticalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDesenvolvedora)
                    .addComponent(jtDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantidade)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlClassificacao)
                    .addComponent(jtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jlConfirmacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlConfirmacao.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlConfirmacao.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlConfirmacaoLayout = new javax.swing.GroupLayout(jlConfirmacao);
        jlConfirmacao.setLayout(jlConfirmacaoLayout);
        jlConfirmacaoLayout.setHorizontalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jbCadastrar)
                .addGap(40, 40, 40)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlConfirmacaoLayout.setVerticalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDados)
                    .addComponent(jlConfirmacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastrar(){
        try {
            JogoVO jVO = new JogoVO();
            jVO.setNome(jtNome.getText());
            jVO.setDesenvolvedora(jtDesenvolvedora.getText());
            jVO.setQuantidade(Integer.parseInt(jtQuantidade.getText()));
            jVO.setClassificacao(jtClassificacao.getText());
            jVO.setValor(Double.parseDouble(jtValor.getText()));

            JogoServicos js = servicos.ServicosFactory.getJogoServicos();

            js.cadastrarJogo(jVO);

            JOptionPane.showMessageDialog(this,
                    "Jogo cadastrado com sucesso! ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        jtNome.setBackground(Color.white);
        jtDesenvolvedora.setBackground(Color.white);
        jtClassificacao.setBackground(Color.white);
        jtQuantidade.setBackground(Color.white);
        jtValor.setBackground(Color.white);
    }
    
    private void limpar() {
        jtNome.setText(null);
        jtClassificacao.setText(null);
        jtDesenvolvedora.setText(null);
        jtQuantidade.setText(null);
        jtValor.setText(null);
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
        jtNome.grabFocus();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()) {
            jtNome.setBackground(Color.RED);
        } else {
            jtNome.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtDesenvolvedoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDesenvolvedoraFocusLost
        if (jtDesenvolvedora.getText().isEmpty()) {
            jtDesenvolvedora.setBackground(Color.RED);
        } else {
            jtDesenvolvedora.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_jtDesenvolvedoraFocusLost

    private void jtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantidadeFocusLost
        if (jtQuantidade.getText().isEmpty()) {
            jtQuantidade.setBackground(Color.RED);
        } else {
            jtQuantidade.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_jtQuantidadeFocusLost

    private void jtClassificacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtClassificacaoFocusLost
        if (jtClassificacao.getText().isEmpty()) {
            jtClassificacao.setBackground(Color.RED);
        } else {
            jtClassificacao.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_jtClassificacaoFocusLost

    private void jtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorFocusLost
        if (jtValor.getText().isEmpty()) {
            jtValor.setBackground(Color.RED);
        } else {
            jtValor.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_jtValorFocusLost
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlClassificacao;
    private javax.swing.JLayeredPane jlConfirmacao;
    private javax.swing.JLayeredPane jlDados;
    private javax.swing.JLabel jlDesenvolvedora;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtClassificacao;
    private javax.swing.JTextField jtDesenvolvedora;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
