package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Aluno;

/**
 *
 * @author Müller Gonçalves & Fernando Aragão
 * @since 19/04/2018 - 13:58
 * @version 1.0
 */
public class UICadAluno extends javax.swing.JFrame {

    Aluno objAluno = new Aluno();

    /**
     * Creates new form UICadAluno
     */
    public UICadAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlN1 = new javax.swing.JLabel();
        jlN2 = new javax.swing.JLabel();
        jlP1 = new javax.swing.JLabel();
        jlP2 = new javax.swing.JLabel();
        jlDisciplina = new javax.swing.JLabel();
        jlTotalAulas = new javax.swing.JLabel();
        jlNumeroPresencas = new javax.swing.JLabel();
        jlRelatorio = new javax.swing.JLabel();
        JScrollPanel = new javax.swing.JScrollPane();
        jtRelatorio = new javax.swing.JTextArea();
        jtNome = new javax.swing.JTextField();
        jtN1 = new javax.swing.JTextField();
        jtN2 = new javax.swing.JTextField();
        jtP1 = new javax.swing.JTextField();
        jtP2 = new javax.swing.JTextField();
        jtTotalAulas = new javax.swing.JTextField();
        jtNumeroPresencas = new javax.swing.JTextField();
        jcLPV = new javax.swing.JCheckBox();
        jcSQI = new javax.swing.JCheckBox();
        jcLPM = new javax.swing.JCheckBox();
        jcLPW = new javax.swing.JCheckBox();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlN1Erro = new javax.swing.JLabel();
        jlN2Erro = new javax.swing.JLabel();
        jlP1Erro = new javax.swing.JLabel();
        jlP2Erro = new javax.swing.JLabel();
        jlTotalAulasErro = new javax.swing.JLabel();
        jlNumeroPresencasErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jlSexo.setText("Sexo:");

        jlN1.setText("N1:");

        jlN2.setText("N2:");

        jlP1.setText("P1:");

        jlP2.setText("P2:");

        jlDisciplina.setText("Disciplina:");

        jlTotalAulas.setText("Total de Aulas:");

        jlNumeroPresencas.setText("Número de Presenças:");

        jlRelatorio.setText("Relatório");

        jtRelatorio.setColumns(20);
        jtRelatorio.setRows(5);
        JScrollPanel.setViewportView(jtRelatorio);

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtN1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtN1FocusLost(evt);
            }
        });
        jtN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtN1KeyPressed(evt);
            }
        });

        jtN2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtN2FocusLost(evt);
            }
        });
        jtN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtN2KeyPressed(evt);
            }
        });

        jtP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtP1FocusLost(evt);
            }
        });
        jtP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtP1KeyPressed(evt);
            }
        });

        jtP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtP2FocusLost(evt);
            }
        });
        jtP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtP2KeyPressed(evt);
            }
        });

        jtTotalAulas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTotalAulasFocusLost(evt);
            }
        });
        jtTotalAulas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTotalAulasKeyPressed(evt);
            }
        });

        jtNumeroPresencas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumeroPresencasFocusLost(evt);
            }
        });
        jtNumeroPresencas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumeroPresencasKeyPressed(evt);
            }
        });

        jcLPV.setText("LPV");
        jcLPV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLPVKeyPressed(evt);
            }
        });

        jcSQI.setText("SQI");
        jcSQI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcSQIKeyPressed(evt);
            }
        });

        jcLPM.setText("LPM");
        jcLPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLPMKeyPressed(evt);
            }
        });

        jcLPW.setText("LPW");
        jcLPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLPWKeyPressed(evt);
            }
        });

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyPressed(evt);
            }
        });

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemininoKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlN1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlN2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlP2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlDisciplina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTotalAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumeroPresencas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(JScrollPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtN1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtN2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtP1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtP2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTotalAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNumeroPresencas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcLPV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcSQI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcLPM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jcLPW, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlN1Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlN2Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlP1Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlP2Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTotalAulasErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumeroPresencasErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrFeminino)
                                    .addComponent(jrMasculino)))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jlpDadosLayout.createSequentialGroup()
                                            .addComponent(jlP1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                            .addComponent(jlN2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtN2)))
                                    .addGroup(jlpDadosLayout.createSequentialGroup()
                                        .addComponent(jlN1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlN1Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlN2Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlP1Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlRelatorio)
                                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDadosLayout.createSequentialGroup()
                                            .addComponent(jlTotalAulas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtTotalAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlTotalAulasErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jlpDadosLayout.createSequentialGroup()
                                            .addComponent(jlDisciplina)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jcLPV)
                                                .addComponent(jcLPM))
                                            .addGap(31, 31, 31)
                                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jcLPW)
                                                .addComponent(jcSQI))))
                                    .addGroup(jlpDadosLayout.createSequentialGroup()
                                        .addComponent(jlNumeroPresencas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNumeroPresencas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlNumeroPresencasErro)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtP2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlP2Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(174, 174, 174))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNomeErro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSexo)
                            .addComponent(jrMasculino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrFeminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtTotalAulas)
                                .addComponent(jlTotalAulasErro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlN1)
                                .addComponent(jtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlTotalAulas)
                                .addComponent(jlN1Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroPresencas)
                            .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlN2)
                                .addComponent(jtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtNumeroPresencas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlN2Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlNumeroPresencasErro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlP1)
                            .addComponent(jtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRelatorio)
                            .addComponent(jlP1Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlP2)
                                    .addComponent(jtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlP2Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(JScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcLPV)
                            .addComponent(jcSQI)
                            .addComponent(jlDisciplina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcLPM)
                            .addComponent(jcLPW))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar relatório");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbRelatorio.setText("Relatório");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });
        jbRelatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbRelatorioKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar() {
        try {
            objAluno.setNome(jtNome.getText());
            objAluno.setSexo(bgSexo.getSelection().getActionCommand());
            objAluno.setN1(Double.parseDouble(jtN1.getText()));
            objAluno.setN2(Double.parseDouble(jtN2.getText()));
            objAluno.setP1(Double.parseDouble(jtP1.getText()));
            objAluno.setP2(Double.parseDouble(jtP2.getText()));
            objAluno.setTotalDeAulas(Double.parseDouble(jtTotalAulas.getText()));
            objAluno.setNumeroPresencas(Double.parseDouble(jtNumeroPresencas.getText()));
            ArrayList<String> disciplina = new ArrayList();

            if (!jrMasculino.isSelected() && !jrFeminino.isSelected()) {
                throw new NumberFormatException("Selecione o sexo!");

            }

            if (jcLPV.isSelected()) {
                disciplina.add(jcLPV.getText());
            }
            if (jcLPM.isSelected()) {
                disciplina.add(jcLPM.getText());
            }
            if (jcSQI.isSelected()) {
                disciplina.add(jcSQI.getText());
            }
            if (jcLPW.isSelected()) {
                disciplina.add(jcLPW.getText());
            }

            jbCadastrar.setEnabled(true);

            objAluno.setDisc(disciplina);

            jtNome.setText(null);
            bgSexo.clearSelection();
            jtN1.setText(null);
            jtN2.setText(null);
            jtP1.setText(null);
            jtP2.setText(null);
            jtTotalAulas.setText(null);
            jtNumeroPresencas.setText(null);
            jcLPV.setSelected(false);
            jcLPM.setSelected(false);
            jcSQI.setSelected(false);
            jcLPW.setSelected(false);
            jtNome.setBackground(Color.white);
            jlNomeErro.setIcon(null);
            jtN1.setBackground(Color.white);
            jlN1Erro.setIcon(null);
            jtN2.setBackground(Color.white);
            jlN2Erro.setIcon(null);
            jtP1.setBackground(Color.white);
            jlP1Erro.setIcon(null);
            jtP2.setBackground(Color.white);
            jlP2Erro.setIcon(null);
            jtTotalAulas.setBackground(Color.white);
            jlTotalAulasErro.setIcon(null);
            jtNumeroPresencas.setBackground(Color.white);
            jlNumeroPresencasErro.setIcon(null);
            

            jtRelatorio.setText(jtRelatorio.getText() + "Dados: \n"
                    + objAluno.toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Você cometeu um erro! " + "\nCódigo do erro: " + e.getMessage(),
                    "ERRO FATAL",
                    JOptionPane.ERROR_MESSAGE);
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Você cometeu um erro! " + "\nCódigo do erro: " + e.getMessage(),
                    "ERRO FATAL",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro ocorreu " + "\nCódigo do erro: " + e.getMessage());
        } finally {
            System.out.println("Cadastro efetuado");
        }

    }

    private void limpar() {
        jtRelatorio.setText(null);
    }

    private void relatorio() {
        jtRelatorio.setText(null);
        jtRelatorio.setText("Dados: \n" + objAluno.toString());
    }

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        jtNome.grabFocus();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        relatorio();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbRelatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbRelatorioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            relatorio();
        }
    }//GEN-LAST:event_jbRelatorioKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrMasculino.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jrMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrFeminino.grabFocus();
        }
    }//GEN-LAST:event_jrMasculinoKeyPressed

    private void jrFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtN1.grabFocus();
        }
    }//GEN-LAST:event_jrFemininoKeyPressed

    private void jtN1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtN1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtN2.grabFocus();
        }
    }//GEN-LAST:event_jtN1KeyPressed

    private void jtN2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtN2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtP1.grabFocus();
        }
    }//GEN-LAST:event_jtN2KeyPressed

    private void jtP1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtP1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtP2.grabFocus();
        }
    }//GEN-LAST:event_jtP1KeyPressed

    private void jtP2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtP2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcLPV.grabFocus();
        }
    }//GEN-LAST:event_jtP2KeyPressed

    private void jcLPVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLPVKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcLPM.grabFocus();
        }
    }//GEN-LAST:event_jcLPVKeyPressed

    private void jcLPMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLPMKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcSQI.grabFocus();
        }
    }//GEN-LAST:event_jcLPMKeyPressed

    private void jcSQIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcSQIKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcLPW.grabFocus();
        }
    }//GEN-LAST:event_jcSQIKeyPressed

    private void jcLPWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLPWKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTotalAulas.grabFocus();
        }
    }//GEN-LAST:event_jcLPWKeyPressed

    private void jtTotalAulasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTotalAulasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtNumeroPresencas.grabFocus();
        }
    }//GEN-LAST:event_jtTotalAulasKeyPressed

    private void jtNumeroPresencasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumeroPresencasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jtNumeroPresencasKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()) {
            jtNome.setBackground(Color.RED);
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtNome.setBackground(Color.GREEN);
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtN1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtN1FocusLost
        if (jtN1.getText().isEmpty()) {
            jtN1.setBackground(Color.RED);
            jlN1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtN1.setBackground(Color.GREEN);
            jlN1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtN1FocusLost

    private void jtN2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtN2FocusLost
        if (jtN2.getText().isEmpty()) {
            jtN2.setBackground(Color.RED);
            jlN2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtN2.setBackground(Color.GREEN);
            jlN2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtN2FocusLost

    private void jtP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtP1FocusLost
        if (jtP1.getText().isEmpty()) {
            jtP1.setBackground(Color.RED);
            jlP1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtP1.setBackground(Color.GREEN);
            jlP1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtP1FocusLost

    private void jtP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtP2FocusLost
        if (jtP2.getText().isEmpty()) {
            jtP2.setBackground(Color.RED);
            jlP2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtP2.setBackground(Color.GREEN);
            jlP2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtP2FocusLost

    private void jtTotalAulasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTotalAulasFocusLost
        if (jtTotalAulas.getText().isEmpty()) {
            jtTotalAulas.setBackground(Color.RED);
            jlTotalAulasErro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtTotalAulas.setBackground(Color.GREEN);
            jlTotalAulasErro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtTotalAulasFocusLost

    private void jtNumeroPresencasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumeroPresencasFocusLost
        if (jtNumeroPresencas.getText().isEmpty()) {
            jtNumeroPresencas.setBackground(Color.RED);
            jlNumeroPresencasErro.setIcon(new ImageIcon(getClass().getResource("/imagens/incorreto.png")));
        } else {
            jtNumeroPresencas.setBackground(Color.GREEN);
            jlNumeroPresencasErro.setIcon(new ImageIcon(getClass().getResource("/imagens/correto.png")));
        }
    }//GEN-LAST:event_jtNumeroPresencasFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanel;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JCheckBox jcLPM;
    private javax.swing.JCheckBox jcLPV;
    private javax.swing.JCheckBox jcLPW;
    private javax.swing.JCheckBox jcSQI;
    private javax.swing.JLabel jlDisciplina;
    private javax.swing.JLabel jlN1;
    private javax.swing.JLabel jlN1Erro;
    private javax.swing.JLabel jlN2;
    private javax.swing.JLabel jlN2Erro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlNumeroPresencas;
    private javax.swing.JLabel jlNumeroPresencasErro;
    private javax.swing.JLabel jlP1;
    private javax.swing.JLabel jlP1Erro;
    private javax.swing.JLabel jlP2;
    private javax.swing.JLabel jlP2Erro;
    private javax.swing.JLabel jlRelatorio;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlTotalAulas;
    private javax.swing.JLabel jlTotalAulasErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtN1;
    private javax.swing.JTextField jtN2;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumeroPresencas;
    private javax.swing.JTextField jtP1;
    private javax.swing.JTextField jtP2;
    private javax.swing.JTextArea jtRelatorio;
    private javax.swing.JTextField jtTotalAulas;
    // End of variables declaration//GEN-END:variables
}
