package visao;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Calculo;

/**
 *
 * @author Müller Gonçalves
 * @since 16/04/2018 - 16:03
 * @version 1.0
 */
public class UICadCalculo extends javax.swing.JFrame {

    /**
     * Creates new form UICadCalculo
     */
    public UICadCalculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDados = new javax.swing.JLayeredPane();
        jlX1 = new javax.swing.JLabel();
        jlY1 = new javax.swing.JLabel();
        jlX2 = new javax.swing.JLabel();
        jlY2 = new javax.swing.JLabel();
        jtX1 = new javax.swing.JTextField();
        jtY1 = new javax.swing.JTextField();
        jtX2 = new javax.swing.JTextField();
        jtY2 = new javax.swing.JTextField();
        jlConfirmacao = new javax.swing.JLayeredPane();
        jbVerificar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jlX1.setText("X1:");

        jlY1.setText("Y1:");

        jlX2.setText("X2:");

        jlY2.setText("Y2:");

        jtX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtX1KeyPressed(evt);
            }
        });

        jtY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtY1KeyPressed(evt);
            }
        });

        jtX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtX2KeyPressed(evt);
            }
        });

        jtY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtY2KeyPressed(evt);
            }
        });

        jlDados.setLayer(jlX1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlY1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlX2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jlY2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtX1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtY1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtX2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtY2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlDadosLayout = new javax.swing.GroupLayout(jlDados);
        jlDados.setLayout(jlDadosLayout);
        jlDadosLayout.setHorizontalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlY2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtY2))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlX2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtX2))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlY1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtY1))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jlX1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlDadosLayout.setVerticalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlX1)
                    .addComponent(jtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlY1)
                    .addComponent(jtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlX2)
                    .addComponent(jtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlY2)
                    .addComponent(jtY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jlConfirmacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirmação"));

        jbVerificar.setText("Verificar");
        jbVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerificarActionPerformed(evt);
            }
        });
        jbVerificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbVerificarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlConfirmacao.setLayer(jbVerificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlConfirmacao.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlConfirmacaoLayout = new javax.swing.GroupLayout(jlConfirmacao);
        jlConfirmacao.setLayout(jlConfirmacaoLayout);
        jlConfirmacaoLayout.setHorizontalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jbVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jlConfirmacaoLayout.setVerticalGroup(
            jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlConfirmacaoLayout.createSequentialGroup()
                .addGroup(jlConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVerificar)
                    .addComponent(jbLimpar))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDados)
                    .addComponent(jlConfirmacao))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificarActionPerformed
        verificar();
        limpar();
    }//GEN-LAST:event_jbVerificarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbVerificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbVerificarKeyPressed
        verificar();
        limpar();
    }//GEN-LAST:event_jbVerificarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        limpar();
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jtX1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtX1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtY1.grabFocus();
        }
    }//GEN-LAST:event_jtX1KeyPressed

    private void jtY1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtY1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtX2.grabFocus();
        }
    }//GEN-LAST:event_jtY1KeyPressed

    private void jtX2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtX2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtY2.grabFocus();
        }
    }//GEN-LAST:event_jtX2KeyPressed

    private void jtY2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtY2KeyPressed
        verificar();
        limpar();
        jtX1.grabFocus();
    }//GEN-LAST:event_jtY2KeyPressed
    
    public void verificar(){
        Calculo objCalculo = new Calculo();
        
        objCalculo.setX1(Double.parseDouble(jtX1.getText()));
        objCalculo.setY1(Double.parseDouble(jtY1.getText()));
        objCalculo.setX2(Double.parseDouble(jtX2.getText()));
        objCalculo.setY2(Double.parseDouble(jtY2.getText()));
        
        JOptionPane.showMessageDialog(
                this,
                "Dados: \n" + objCalculo.toString(),
                "Relatório",
                JOptionPane.PLAIN_MESSAGE);
    }
    
    public void limpar(){
        jtX1.setText(null);
        jtY1.setText(null);
        jtX2.setText(null);
        jtY2.setText(null);
        jtX1.grabFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadCalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbVerificar;
    private javax.swing.JLayeredPane jlConfirmacao;
    private javax.swing.JLayeredPane jlDados;
    private javax.swing.JLabel jlX1;
    private javax.swing.JLabel jlX2;
    private javax.swing.JLabel jlY1;
    private javax.swing.JLabel jlY2;
    private javax.swing.JTextField jtX1;
    private javax.swing.JTextField jtX2;
    private javax.swing.JTextField jtY1;
    private javax.swing.JTextField jtY2;
    // End of variables declaration//GEN-END:variables
}
