/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.JOptionPane;
import modelo.Pessoa;

/**
 *
 * @author Alunos
 */
public class GUICardPessoa extends javax.swing.JFrame {

    /**
     * Creates new form GUICardPessoa
     */
    public GUICardPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgop = new javax.swing.ButtonGroup();
        JLPDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminio = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResposta = new javax.swing.JTextArea();
        jr1 = new javax.swing.JRadioButton();
        jr2 = new javax.swing.JRadioButton();
        jbVer = new javax.swing.JButton();
        JLPAcoes = new javax.swing.JLayeredPane();
        jbCadatrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLPDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jlSexo.setText("Sexo");

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");

        bgSexo.add(jrFeminio);
        jrFeminio.setText("Feminino");
        jrFeminio.setActionCommand("Feminino");

        jtResposta.setColumns(20);
        jtResposta.setRows(5);
        jScrollPane1.setViewportView(jtResposta);

        bgop.add(jr1);
        jr1.setText("1");
        jr1.setActionCommand("1");

        bgop.add(jr2);
        jr2.setText("2");
        jr2.setActionCommand("2");

        jbVer.setText("Ver");

        JLPDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jrFeminio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jr2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPDados.setLayer(jbVer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JLPDadosLayout = new javax.swing.GroupLayout(JLPDados);
        JLPDados.setLayout(JLPDadosLayout);
        JLPDadosLayout.setHorizontalGroup(
            JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLPDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JLPDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JLPDadosLayout.createSequentialGroup()
                        .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JLPDadosLayout.createSequentialGroup()
                                .addComponent(jlSexo)
                                .addGap(41, 41, 41)
                                .addComponent(jrMasculino)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLPDadosLayout.createSequentialGroup()
                                .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JLPDadosLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jbVer))
                                    .addComponent(jr1))
                                .addGap(21, 21, 21)))
                        .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jr2)
                            .addComponent(jrFeminio))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        JLPDadosLayout.setVerticalGroup(
            JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLPDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(JLPDadosLayout.createSequentialGroup()
                .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JLPDadosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlNome))
                    .addGroup(JLPDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jrMasculino)
                    .addComponent(jrFeminio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(JLPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr1)
                    .addComponent(jr2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVer)
                .addGap(15, 15, 15))
        );

        JLPAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadatrar.setText("Cdastrar");
        jbCadatrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadatrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        JLPAcoes.setLayer(jbCadatrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLPAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JLPAcoesLayout = new javax.swing.GroupLayout(JLPAcoes);
        JLPAcoes.setLayout(JLPAcoesLayout);
        JLPAcoesLayout.setHorizontalGroup(
            JLPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLPAcoesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jbCadatrar)
                .addGap(51, 51, 51)
                .addComponent(jbLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JLPAcoesLayout.setVerticalGroup(
            JLPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLPAcoesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(JLPAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadatrar)
                    .addComponent(jbLimpar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLPDados)
                    .addComponent(JLPAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLPDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLPAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        //estanciando classe Pessoa
        Pessoa pp = new Pessoa();
        //etrada de dados
        pp.setNome(jtNome.getText());
        
        pp.setSexo(bgSexo.getSelection().getActionCommand());
        
        String op = bgop.getSelection().getActionCommand();
        
        /*if (jrMasculino.isSelected())
                pp.setSexo(jrMasculino.getText());
            {
                pp.setSexo(jrFeminio.getText());
            }*/
        JOptionPane.showMessageDialog(this,
                "Resultado \n" + pp.toString(),
                "SAIDA",
                JOptionPane.PLAIN_MESSAGE);
        
        jtResposta.setText(jtResposta.getText() + "\n"
                + "Dados: " + pp.verificarOP(op) + "\n");
        
        

    }//fecha cadasrtrar
    private void limpar(){
        jtNome.setText(null);
        //radio se group (buttonGroup)!
        /*jrMasculino.setSelected(false);
        jrFeminio.setSelected(false);*/
        //limpando radio button
        bgSexo.clearSelection();
    }//fecha limpar
    private void jbCadatrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadatrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbCadatrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICardPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICardPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICardPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICardPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICardPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane JLPAcoes;
    private javax.swing.JLayeredPane JLPDados;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadatrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbVer;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JRadioButton jr1;
    private javax.swing.JRadioButton jr2;
    private javax.swing.JRadioButton jrFeminio;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextArea jtResposta;
    // End of variables declaration//GEN-END:variables
}
